<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>500 Internal Server Error</title>
    <link>https://discuss.redash.io/t/500-internal-server-error/8316</link>
    <description>Hi, I have been using Redash for a while now on my Kubernetes environment. But sometimes I keep getting &quot;Internal Server Error&quot; when I try to open my redash page but when I refresh the page a few times, the page will load normally without the error again. Does anybody experience this before?</description>
    
    <lastBuildDate>Tue, 07 Dec 2021 12:22:42 +0000</lastBuildDate>
    <category>Support</category>
    <atom:link href="https://discuss.redash.io/t/500-internal-server-error/8316.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>500 Internal Server Error</title>
        <dc:creator><![CDATA[gnnivlek]]></dc:creator>
        <description><![CDATA[
            <p>Hi, I have solved the issue by using this solution and applying it to /app/redash/models/base.py<br>
<a href="https://github.com/getredash/redash/issues/4675#issuecomment-592574785" class="inline-onebox" rel="noopener nofollow ugc">"OperationalError: server closed the connection unexpectedly" on SQL: ‘SELECT … FROM organizations’ · Issue #4675 · getredash/redash · GitHub</a>.</p>
<p>Apparently the docker version of Redash does not have pool_pre_ping option so I have to mount it manually to the deployment.<br>
Thank you for the helps.</p>
          <p><a href="https://discuss.redash.io/t/500-internal-server-error/8316/6">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/500-internal-server-error/8316/6</link>
        <pubDate>Thu, 22 Apr 2021 02:41:21 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8316-6</guid>
        <source url="https://discuss.redash.io/t/500-internal-server-error/8316.rss">500 Internal Server Error</source>
      </item>
      <item>
        <title>500 Internal Server Error</title>
        <dc:creator><![CDATA[gnnivlek]]></dc:creator>
        <description><![CDATA[
            <p>I have added “SQLALCHEMY_ENABLE_POOL_PRE_PING”: true on the environment variable but I’m still getting this error. Currently I’m using Redash version 8.0.2.b37747 that was pulled from docker registry.</p>
          <p><a href="https://discuss.redash.io/t/500-internal-server-error/8316/5">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/500-internal-server-error/8316/5</link>
        <pubDate>Mon, 19 Apr 2021 04:52:09 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8316-5</guid>
        <source url="https://discuss.redash.io/t/500-internal-server-error/8316.rss">500 Internal Server Error</source>
      </item>
      <item>
        <title>500 Internal Server Error</title>
        <dc:creator><![CDATA[gnnivlek]]></dc:creator>
        <description><![CDATA[
            <p>Thanks k4s1m &amp; xavier-d for the responses.<br>
Here is the log when this event occured. When I first access the page, it returned the Internal Server Error message but as I refresh the page, it successfully load the login page</p>
<p>[2021-04-17 05:39:56,523][PID:919][ERROR][redash] Exception on /login [GET]<br>
Traceback (most recent call last):<br>
File “/usr/local/lib/python2.7/dist-packages/flask/app.py”, line 1988, in wsgi_app<br>
response = self.full_dispatch_request()<br>
File “/usr/local/lib/python2.7/dist-packages/flask/app.py”, line 1641, in full_dispatch_request<br>
rv = self.handle_user_exception(e)<br>
File “/usr/local/lib/python2.7/dist-packages/flask_restful/<strong>init</strong>.py”, line 271, in error_router<br>
return original_handler(e)<br>
File “/usr/local/lib/python2.7/dist-packages/flask/app.py”, line 1544, in handle_user_exception<br>
reraise(exc_type, exc_value, tb)<br>
File “/usr/local/lib/python2.7/dist-packages/flask/app.py”, line 1639, in full_dispatch_request<br>
rv = self.dispatch_request()<br>
File “/usr/local/lib/python2.7/dist-packages/flask/app.py”, line 1625, in dispatch_request<br>
return self.view_functions<a href="https://discuss.redash.io">rule.endpoint</a><br>
File “/usr/local/lib/python2.7/dist-packages/flask_limiter/extension.py”, line 442, in __inner<br>
return obj(*a, **k)<br>
File “/app/redash/handlers/authentication.py”, line 143, in login<br>
if current_org == None and not settings.MULTI_ORG:<br>
File “/usr/local/lib/python2.7/dist-packages/werkzeug/local.py”, line 365, in <br>
<strong>eq</strong> = lambda x, o: x._get_current_object() == o<br>
File “/usr/local/lib/python2.7/dist-packages/werkzeug/local.py”, line 302, in _get_current_object<br>
return self.__local()<br>
File “/app/redash/authentication/org_resolving.py”, line 18, in _get_current_org<br>
g .org = Organization.get_by_slug(slug)<br>
File “/app/redash/models/organizations.py”, line 33, in get_by_slug<br>
return cls.query.filter(cls.slug == slug).first()<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 2895, in first<br>
ret = list(self[0:1])<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 2687, in <strong>getitem</strong><br>
return list(res)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 2995, in <strong>iter</strong><br>
return self._execute_and_instances(context)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py”, line 3018, in _execute_and_instances<br>
result = conn.execute(querycontext.statement, self._params)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 948, in execute<br>
return meth(self, multiparams, params)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py”, line 269, in _execute_on_connection<br>
return connection._execute_clauseelement(self, multiparams, params)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1060, in _execute_clauseelement<br>
compiled_sql, distilled_params<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1200, in _execute_context<br>
context)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1413, in _handle_dbapi_exception<br>
exc_info<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py”, line 265, in raise_from_cause<br>
reraise(type(exception), exception, tb=exc_tb, cause=cause)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py”, line 1193, in _execute_context<br>
context)<br>
File “/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py”, line 509, in do_execute<br>
cursor.execute(statement, parameters)<br>
OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly<br>
This probably means the server terminated abnormally<br>
before or while processing the request.<br>
[SQL: ‘SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings \nFROM organizations \nWHERE organizations.slug = %(slug_1)s \n LIMIT %(param_1)s’] [parameters: {‘slug_1’: ‘default’, ‘param_1’: 1}] (Background on this error at: <a href="http://sqlalche.me/e/e3q8" rel="noopener nofollow ugc">http://sqlalche.me/e/e3q8</a> )<br>
[2021-04-17 05:39:56,527][PID:919][INFO][metrics] method=GET path=/login endpoint=redash_login status=500 content_type=? content_length=-1 duration=10.03 query_count=0 query_duration=0.00<br>
[2021-04-17 05:39:59,427][PID:1121][INFO][metrics] method=GET path=/login endpoint=redash_login status=200 content_type=text/html; charset=utf-8 content_length=1827 duration=29.98 query_count=1 query_duration=4.42</p>
          <p><a href="https://discuss.redash.io/t/500-internal-server-error/8316/4">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/500-internal-server-error/8316/4</link>
        <pubDate>Sat, 17 Apr 2021 05:52:18 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8316-4</guid>
        <source url="https://discuss.redash.io/t/500-internal-server-error/8316.rss">500 Internal Server Error</source>
      </item>
      <item>
        <title>500 Internal Server Error</title>
        <dc:creator><![CDATA[xavier-d]]></dc:creator>
        <description><![CDATA[
            <p>As K4s1m was saying without any logs it will be complicated; I faced same kind of issue solved by <strong>SQLALCHEMY_ENABLE_POOL_PRE_PING: “true”</strong> but it could be completely something else …</p>
          <p><a href="https://discuss.redash.io/t/500-internal-server-error/8316/3">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/500-internal-server-error/8316/3</link>
        <pubDate>Fri, 16 Apr 2021 17:57:37 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8316-3</guid>
        <source url="https://discuss.redash.io/t/500-internal-server-error/8316.rss">500 Internal Server Error</source>
      </item>
      <item>
        <title>500 Internal Server Error</title>
        <dc:creator><![CDATA[k4s1m]]></dc:creator>
        <description><![CDATA[
            <p>This doesn’t sound normal. Can you share any information about the failures? Your logs? Have you restarted everything?</p>
          <p><a href="https://discuss.redash.io/t/500-internal-server-error/8316/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/500-internal-server-error/8316/2</link>
        <pubDate>Fri, 16 Apr 2021 16:17:22 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8316-2</guid>
        <source url="https://discuss.redash.io/t/500-internal-server-error/8316.rss">500 Internal Server Error</source>
      </item>
      <item>
        <title>500 Internal Server Error</title>
        <dc:creator><![CDATA[gnnivlek]]></dc:creator>
        <description><![CDATA[
            <p>Hi, I have been using Redash for a while now on my Kubernetes environment. But sometimes I keep getting “Internal Server Error” when I try to open my redash page but when I refresh the page a few times, the page will load normally without the error again. Does anybody experience this before?</p>
          <p><a href="https://discuss.redash.io/t/500-internal-server-error/8316/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/500-internal-server-error/8316/1</link>
        <pubDate>Fri, 16 Apr 2021 04:12:07 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8316-1</guid>
        <source url="https://discuss.redash.io/t/500-internal-server-error/8316.rss">500 Internal Server Error</source>
      </item>
  </channel>
</rss>
