<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>(2006, &quot;Can’t connect to MySQL server on XXXXXXXXXXXXXX (110)</title>
    <link>https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127</link>
    <description>Hi Team,

We have received sometimes the below docker logs error from the worker when the query is trying to run. Am I think it correctly, that we received this errror when the connection pool is full? Or What is caused this type of error?

Traceback (most recent call last):
  File &quot;/app/redash/tasks/queries/execution.py&quot;, line 188, in run
    data, error = query_runner.run_query(annotated_query, self.user)
  File &quot;/app/redash/query_runner/mysql.py&quot;, line 162, in run_query
    connection = self._connection()
  File &quot;/app/redash/query_runner/mysql.py&quot;, line 121, in _connection
    connection = MySQLdb.connect(**params)
  File &quot;/usr/local/lib/python3.7/site-packages/MySQLdb/__init__.py&quot;, line 85, in Connect
    return Connection(*args, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py&quot;, line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2006, &quot;Can&#39;t connect to MySQL server on  XXXXXXXXXXXXXX

![image|690x153](upload://e06zJqpH8zcZb6sN9rkiNtqrIvV.png)</description>
    
    <lastBuildDate>Tue, 18 Oct 2022 06:10:13 +0000</lastBuildDate>
    <category>Uncategorized</category>
    <atom:link href="https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>(2006, &quot;Can’t connect to MySQL server on XXXXXXXXXXXXXX (110)</title>
        <dc:creator><![CDATA[adam09066]]></dc:creator>
        <description><![CDATA[
            <p>There was a IP route issue on the local host.</p>
          <p><a href="https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127/2</link>
        <pubDate>Tue, 18 Oct 2022 06:10:13 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11127-2</guid>
        <source url="https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127.rss">(2006, &quot;Can’t connect to MySQL server on XXXXXXXXXXXXXX (110)</source>
      </item>
      <item>
        <title>(2006, &quot;Can’t connect to MySQL server on XXXXXXXXXXXXXX (110)</title>
        <dc:creator><![CDATA[adam09066]]></dc:creator>
        <description><![CDATA[
            <p>Hi Team,</p>
<p>We have received sometimes the below docker logs error from the worker when the query is trying to run. Am I think it correctly, that we received this errror when the connection pool is full? Or What is caused this type of error?</p>
<p>Traceback (most recent call last):<br>
File “/app/redash/tasks/queries/execution.py”, line 188, in run<br>
data, error = query_runner.run_query(annotated_query, self.user)<br>
File “/app/redash/query_runner/mysql.py”, line 162, in run_query<br>
connection = self._connection()<br>
File “/app/redash/query_runner/mysql.py”, line 121, in _connection<br>
connection = MySQLdb.connect(**params)<br>
File “/usr/local/lib/python3.7/site-packages/MySQLdb/<strong>init</strong>.py”, line 85, in Connect<br>
return Connection(*args, **kwargs)<br>
File “/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py”, line 208, in <strong>init</strong><br>
super(Connection, self).<strong>init</strong>(*args, **kwargs2)<br>
_mysql_exceptions.OperationalError: (2006, "Can’t connect to MySQL server on  XXXXXXXXXXXXXX</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://global.discourse-cdn.com/standard17/uploads/redash1/original/2X/6/6221814aae1314afedda85d3b0be56c76ae66bd3.png" data-download-href="/uploads/short-url/e06zJqpH8zcZb6sN9rkiNtqrIvV.png?dl=1" title="image" rel="noopener nofollow ugc"><img src="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/6/6221814aae1314afedda85d3b0be56c76ae66bd3_2_690x153.png" alt="image" data-base62-sha1="e06zJqpH8zcZb6sN9rkiNtqrIvV" width="690" height="153" srcset="https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/6/6221814aae1314afedda85d3b0be56c76ae66bd3_2_690x153.png, https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/6/6221814aae1314afedda85d3b0be56c76ae66bd3_2_1035x229.png 1.5x, https://global.discourse-cdn.com/standard17/uploads/redash1/optimized/2X/6/6221814aae1314afedda85d3b0be56c76ae66bd3_2_1380x306.png 2x" data-dominant-color="F9FAFA"></a></div><p></p>
          <p><a href="https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127/1</link>
        <pubDate>Wed, 12 Oct 2022 09:39:49 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-11127-1</guid>
        <source url="https://discuss.redash.io/t/2006-can-t-connect-to-mysql-server-on-xxxxxxxxxxxxxx-110/11127.rss">(2006, &quot;Can’t connect to MySQL server on XXXXXXXXXXXXXX (110)</source>
      </item>
  </channel>
</rss>
