<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Dashboard API error</title>
    <link>https://discuss.redash.io/t/dashboard-api-error/9002</link>
    <description>### Issue Summary

Hello community members,

When I try to call 

```
http://redash.xyz.com/api/dashboards
```
I  am getting  below error

```
{
&quot;message&quot;: &quot;Internal Server Error&quot;
}
```

### Technical details:
looking  into logs, I am getting below

```
[2021-08-31 12:26:37,580][PID:122587][ERROR][redash] Exception on /api/dashboards [GET]
Traceback (most recent call last):
  File &quot;/usr/local/lib/python2.7/dist-packages/flask/app.py&quot;, line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File &quot;/usr/local/lib/python2.7/dist-packages/flask/app.py&quot;, line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File &quot;/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py&quot;, line 477, in wrapper
    resp = resource(*args, **kwargs)
  File &quot;/usr/local/lib/python2.7/dist-packages/flask_login/utils.py&quot;, line 228, in decorated_view
    return func(*args, **kwargs)
  File &quot;/usr/local/lib/python2.7/dist-packages/flask/views.py&quot;, line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File &quot;/opt/redash/redash.7.0.0.b17535/redash/handlers/base.py&quot;, line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File &quot;/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py&quot;, line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File &quot;/opt/redash/redash.7.0.0.b17535/redash/permissions.py&quot;, line 48, in decorated
    return fn(*args, **kwargs)
  File &quot;/opt/redash/redash.7.0.0.b17535/redash/handlers/dashboards.py&quot;, line 75, in get
    serializer=serialize_dashboard,
  File &quot;/opt/redash/redash.7.0.0.b17535/redash/handlers/base.py&quot;, line 108, in paginate
    items = [serializer(result) for result in results.items]
  File &quot;/opt/redash/redash.7.0.0.b17535/redash/serializers.py&quot;, line 213, in serialize_dashboard
    &#39;user&#39;: obj.user.to_dict(),
AttributeError: &#39;NoneType&#39; object has no attribute &#39;to_dict&#39;
```
* Redash Version: 7
* Browser/OS:  Chrom
* How did you install Redash: Legacy install</description>
    
    <lastBuildDate>Wed, 01 Sep 2021 13:06:25 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/dashboard-api-error/9002.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Thank you for linking that issue! I had totally forgotten about it. Since this isn‚Äôt a regression from V8 it won‚Äôt be fixed before the V10 release but we‚Äôll see about arranging a fix after that.</p>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/8">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/8</link>
        <pubDate>Wed, 01 Sep 2021 13:06:25 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-8</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[mali]]></dc:creator>
        <description><![CDATA[
            <p>found the cause. this issue is related to below</p>
<aside class="onebox githubissue" data-onebox-src="https://github.com/getredash/redash/issues/4803">
  <header class="source">

      <a href="https://github.com/getredash/redash/issues/4803" target="_blank" rel="noopener nofollow ugc">github.com/getredash/redash</a>
  </header>

  <article class="onebox-body">
    <div class="github-row">
  <div class="github-icon-container" title="Issue">
	  <svg width="60" height="60" class="github-icon" viewBox="0 0 14 16" aria-hidden="true"><path d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg>
  </div>

  <div class="github-info-container">
    <h4>
      <a href="https://github.com/getredash/redash/issues/4803" target="_blank" rel="noopener nofollow ugc">AttributeError exception causing API 500 errors being experienced when searching Dashboards</a>
    </h4>

    <div class="github-info">
      <div class="date">
        opened <span class="discourse-local-date" data-format="ll" data-date="2020-04-14" data-time="19:19:42" data-timezone="UTC">07:19PM - 14 Apr 20 UTC</span>
      </div>


      <div class="user">
        <a href="https://github.com/Ralnoc" target="_blank" rel="noopener nofollow ugc">
          <img alt="Ralnoc" src="https://avatars.githubusercontent.com/u/2515191?v=4" class="onebox-avatar-inline" width="20" height="20">
          Ralnoc
        </a>
      </div>
    </div>

    <div class="labels">
    </div>
  </div>
</div>

  <div class="github-row">
    <p class="github-body-container">&lt;!--

We use GitHub only for bug reports üêõ

Anything else should be posted t<span class="show-more-container"><a href="https://discuss.redash.io" rel="noopener" class="show-more">‚Ä¶</a></span><span class="excerpt hidden">o http://discuss.redash.io üë´

üö®For support, help &amp; questions use http://discuss.redash.io/c/support
üí°For feature requests &amp; ideas use http://discuss.redash.io/c/feature-requests

**Found a security vulnerability?** Please email security@redash.io to report any security vulnerabilities. We will acknowledge receipt of your vulnerability and strive to send you regular updates about our progress. If you're curious about the status of your disclosure please feel free to email us again. If you want to encrypt your disclosure email, you can use this PGP key.

--&gt;

### Issue Summary

In some situations, when doing a search for dashboards is resulting in an `AttributeError` exception on `obj.user.to_dict()`. I have been unable to yet pinpoint any direct cause, only the process that leads up to the issue. In addition, the issue only manifests when searching, and only with some characters, not all. Primarily if there is a large number of results. If I just navigate through the pages on the Dashboards list, there is no issues experienced.

The order that I have been able to trace through the code, which leads to this problem is this:

User types in search in the Dashboards page of Re:Dash
`DashboardListResource` is called to search DB for dashboards the meets the query using `models.Dashboard.search` - Successful
`DashboardListResource` orders the results of that query - Successful
`DashboardListResource` calls `serialize_dashboard` as part of the pagination process for the the results of the order_results - Successful
`handlers.base.paginate` paginates the results and passes it over to `serialize_dashboards` - Successful
`serialize_dashboard` executes to serialize the paginated results to return - Fails ( `items = [serializer(result) for result in results.items]` fails with the exception `AttributeError: 'NoneType' object has no attribute 'to_dict')`

This issue appears to have started after we upgraded from Re:Dash 6.0.0 to 8.0.0. We used the normal DB upgrade scripts as part of the upgrade process. We have tested the Queries and Users API endpoints and none of them throw this exception. It only happens on Dashboards and only when doing a search.

We suspect it is possible an issue with SQLAlchemy related to: https://github.com/sqlalchemy/sqlalchemy/issues/3650

This is the traceback being experienced:

```
[2020-04-14 12:10:05,461] ERROR in app: Exception on /api/dashboards [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py\", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 67, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/dashboards.py", line 76, in get
    serializer=serialize_dashboard,
  File "/app/redash/handlers/base.py", line 108, in paginate
    items = [serializer(result) for result in results.items]
  File "/app/redash/serializers/__init__.py", line 214, in serialize_dashboard
    'user': obj.user.to_dict(),
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

### Steps to Reproduce

1. Have a number of Dashboards with content in them/ My testing was done with 12 to 15.
2. Set the Page Size (Results count) to 5 on the Dashboards page
3. Enter a one letter search that matches most of your results.
4. It will either immediately throw the exception with the API returning a 500, or if you click on the next page it will.

This is a breaking behavior the impairs the ability to Navigate Dashboards.

### Technical details:

* Redash Version: 8.0.0+b32245
* Browser/OS: Chrome (Running on Linux, impacts all users, regardless of OS or Browser)
* How did you install Redash: Docker</span></p>
  </div>

  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>

          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/7">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/7</link>
        <pubDate>Wed, 01 Sep 2021 10:46:08 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-7</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[mali]]></dc:creator>
        <description><![CDATA[
            <p>made call to individual dashboards using ‚Äú/api/dashboards/&lt;dashboard_slug&gt;‚Äù and all of them returning  200 <img src="https://emoji.discourse-cdn.com/twitter/frowning.png?v=10" title=":frowning:" class="emoji" alt=":frowning:"></p>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/6">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/6</link>
        <pubDate>Wed, 01 Sep 2021 08:07:18 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-6</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[mali]]></dc:creator>
        <description><![CDATA[
            <p>yes. till page=27 it is giving 500 but on  page=28 is it giving ‚Äúmessage‚Äù: ‚ÄúPage is out of range.‚Äù</p>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/5">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/5</link>
        <pubDate>Wed, 01 Sep 2021 07:13:30 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-5</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Interesting thought! Do you see a 500 error when you page through your database list?</p>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/4">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/4</link>
        <pubDate>Tue, 31 Aug 2021 16:50:09 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-4</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[mali]]></dc:creator>
        <description><![CDATA[
            <p>not a new installation, it is there from couple of years. GUI is working fine but we never tried API. My intuition is that something is wrong with some dashboard which is stopping fetching all other dashboards.</p>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/3">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/3</link>
        <pubDate>Tue, 31 Aug 2021 14:07:39 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-3</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Is this a new installation of Redash? Has it ever worked?</p>
<p>This looks like an environment issue to me but there‚Äôs not enough data to say for sure.</p>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/2</link>
        <pubDate>Tue, 31 Aug 2021 13:47:13 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-2</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
      <item>
        <title>Dashboard API error</title>
        <dc:creator><![CDATA[mali]]></dc:creator>
        <description><![CDATA[
            <h3>
<a name="issue-summary-1" class="anchor" href="https://discuss.redash.io#issue-summary-1"></a>Issue Summary</h3>
<p>Hello community members,</p>
<p>When I try to call</p>
<pre><code class="lang-auto">http://redash.xyz.com/api/dashboards
</code></pre>
<p>I  am getting  below error</p>
<pre><code class="lang-auto">{
"message": "Internal Server Error"
}
</code></pre>
<h3>
<a name="technical-details-2" class="anchor" href="https://discuss.redash.io#technical-details-2"></a>Technical details:</h3>
<p>looking  into logs, I am getting below</p>
<pre><code class="lang-auto">[2021-08-31 12:26:37,580][PID:122587][ERROR][redash] Exception on /api/dashboards [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/redash/redash.7.0.0.b17535/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/redash/redash.7.0.0.b17535/redash/permissions.py", line 48, in decorated
    return fn(*args, **kwargs)
  File "/opt/redash/redash.7.0.0.b17535/redash/handlers/dashboards.py", line 75, in get
    serializer=serialize_dashboard,
  File "/opt/redash/redash.7.0.0.b17535/redash/handlers/base.py", line 108, in paginate
    items = [serializer(result) for result in results.items]
  File "/opt/redash/redash.7.0.0.b17535/redash/serializers.py", line 213, in serialize_dashboard
    'user': obj.user.to_dict(),
AttributeError: 'NoneType' object has no attribute 'to_dict'
</code></pre>
<ul>
<li>Redash Version: 7</li>
<li>Browser/OS:  Chrom</li>
<li>How did you install Redash: Legacy install</li>
</ul>
          <p><a href="https://discuss.redash.io/t/dashboard-api-error/9002/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/dashboard-api-error/9002/1</link>
        <pubDate>Tue, 31 Aug 2021 12:32:17 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9002-1</guid>
        <source url="https://discuss.redash.io/t/dashboard-api-error/9002.rss">Dashboard API error</source>
      </item>
  </channel>
</rss>
